clone:
  depth: full
pipelines:
  default:
    - step:
        image: node:12.13.0
        caches:
          - node
        script:
          #Deploy
          - mkdir -p ~/.ssh
          - cat my_known_hosts >> ~/.ssh/known_hosts
          - (umask 077; echo $SSH_PRIVATE_KEY | base64 --decode -i > ~/.ssh/id_rsa)
          - git remote add server $DOCEAN_GIT_REPO
          - git push server master
